version: '3'
services:
  docker-centos-vnc:
    privileged: true
    tty: true
    image: terwer/centos:7
    container_name: docker-centos
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5901:5901
    volumes:
      - ./share:/share
      - ./sys/fs/cgroup:/sys/fs/cgroup:ro